version: "3"
services:
  home-dash-client:
    image: home-dash-client:latest
    hostname: home-dash-client
    container_name: home-dash-client
    # build: ./home-dash-client
    ports:
      - "80:${CLIENT_HTTP_PORT}"
      - "443:${CLIENT_HTTPS_PORT}"
      - "${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}"
    networks:
      - home-dash
    volumes:
     - ./home-dash-client:/app:rw
     - client_node_modules:/app/node_modules
    environment:
      HOME_DASH_API_ROUTE: http://home-dash-server:8080/home-dash-api
      HOME_DASH_DOMAIN: https://dev.home.local
      HTTP_PORT: ${CLIENT_HTTP_PORT}
      HTTPS_PORT: ${CLIENT_HTTPS_PORT}
      WEBPACK_DEV_SERVER_PORT: ${WEBPACK_DEV_SERVER_PORT}
    command: ["npm", "run", "dev"]
    # command: ["./wait-for-it.sh", "npm", "run", "dev"]
  home-dash-server:
    hostname: home-dash-server
    container_name: home-dash-server
    build: ./home-dash-server
    image: home-dash-server:latest
    ports:
      - "${SERVER_HTTP_PORT}:8080"
      - "${SERVER_HTTPS_PORT}:8443"
    volumes:
      - ./home-dash-server:/app:rw
      - server_node_modules:${PWD}/home-dash-server/node_modules
    environment:
      NEST_CLIENT_ID: ${NEST_CLIENT_ID}
      NEST_SECRET_ID: ${NEST_SECRET_ID}
      HTTP_PORT: 8080
      HTTPS_PORT: 8443
      HOME_DASH_NEST_REDIRECT_URL: ${HOME_DASH_NEST_REDIRECT_URL}
    networks:
      - home-dash
    command: ["npm", "run", "dev"]
  # home-dash-db:
  #   image: mongo:latest
  #   hostname: home-dash-db
  #   container_name: home-dash-db
  #   environment:
  #       MONGO_INITDB_ROOT_USERNAME: root
  #       MONGO_INITDB_ROOT_PASSWORD: example
  #   networks:
  #     - home-dash
  #   ports:
  #     - 27017:27017
volumes:
  # client_app:
  client_node_modules:
  # server_app:
  server_node_modules:
networks:
  home-dash:
    driver: bridge
