import PropTypes from 'prop-types';

const {
	bool, number, shape, string,
} = PropTypes;

export const propTypes = {
	classes: PropTypes.shape({
		card: PropTypes.string,
		bullet: PropTypes.string,
		title: PropTypes.string,
		pos: PropTypes.string,
	}).isRequired,
	data: shape({
		ambient_temperature_c: number.isRequired,
		ambient_temperature_f: number.isRequired,
		away_temperature_high_c: number.isRequired,
		away_temperature_high_f: number.isRequired,
		away_temperature_low_c: number.isRequired,
		away_temperature_low_f: number.isRequired,
		can_cool: bool.isRequired,
		can_heat: bool.isRequired,
		device_id: string.isRequired,
		eco_temperature_high_c: number.isRequired,
		eco_temperature_high_f: number.isRequired,
		eco_temperature_low_c: number.isRequired,
		eco_temperature_low_f: number.isRequired,
		fan_timer_active: bool.isRequired,
		fan_timer_duration: number.isRequired,
		fan_timer_timeout: string.isRequired,
		has_fan: bool.isRequired,
		has_leaf: bool.isRequired,
		humidity: number.isRequired,
		hvac_mode: string.isRequired,
		hvac_state: string.isRequired,
		is_locked: bool.isRequired,
		is_online: bool.isRequired,
		is_using_emergency_heat: bool.isRequired,
		label: string.isRequired,
		last_connection: string.isRequired,
		locale: string.isRequired,
		locked_temp_max_c: number.isRequired,
		locked_temp_max_f: number.isRequired,
		locked_temp_min_c: number.isRequired,
		locked_temp_min_f: number.isRequired,
		name: string.isRequired,
		name_long: string.isRequired,
		previous_hvac_mode: string.isRequired,
		software_version: string.isRequired,
		structure_id: string.isRequired,
		sunlight_correction_active: bool.isRequired,
		sunlight_correction_enabled: bool.isRequired,
		target_temperature_c: number.isRequired,
		target_temperature_f: number.isRequired,
		target_temperature_high_c: number.isRequired,
		target_temperature_high_f: number.isRequired,
		target_temperature_low_c: number.isRequired,
		target_temperature_low_f: number.isRequired,
		temperature_scale: string.isRequired,
		time_to_target: string.isRequired,
		time_to_target_training: string.isRequired,
		where_id: string.isRequired,
		where_name: string.isRequired,
	}).isRequired,
};
