---
kind: Service
apiVersion: v1
metadata:
  name: home-dash-server
  namespace: home-dash
  labels:
    contextRoot: home-dash-api
    type: ms
    version: v1
    deployment: stable
spec:
  selector:
    app: home-dash-server
  ports:
  - name: http
    protocol: "TCP"
    port: 80
  - name: https
    protocol: "TCP"
    port: 443
  type: ClusterIP


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: home-dash-server
  labels:
    app: home-dash-server
  namespace: home-dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-dash-server
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: home-dash-server
    spec:     # pod spec
      containers:
      - name: home-dash-server
        image: home-dash-server:dev # image we pushed
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          httpGet:
            path: "/home-dash-api/health"
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: "/home-dash-api/health"
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: default
                key: node.env
          - name: KUBE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: default
                key: kube.env
          - name: POD_NAMESPACE
            value: home-dash
          - name: HTTP_PORT
            value: "80"
          - name: HTTPS_PORT
            value: "443"

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: home-dash-server
  namespace: home-dash
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: home-dash-server
  targetCPUUtilizationPercentage: 1000


